// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

namespace Persistence.Migrations
{
    [DbContext(typeof(GameTableContext))]
    [Migration("20211210181030_FixNames")]
    partial class FixNames
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Model.Cards.Field", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Col")
                        .HasColumnType("int");

                    b.Property<int>("Color")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Owner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Row")
                        .HasColumnType("int");

                    b.Property<int>("SetNumber")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("UpgradeCost")
                        .HasColumnType("int");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TableCards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Col = 2,
                            Color = 8,
                            Description = "This is the start point.",
                            Image = "url('../../assets/start-tile.png')",
                            Level = 0,
                            Name = "Go",
                            Rent = "",
                            Row = 2,
                            SetNumber = 1,
                            Type = 5,
                            UpgradeCost = 0,
                            Value = 200
                        },
                        new
                        {
                            Id = 2,
                            Col = 2,
                            Color = 0,
                            Description = "A famous bar amoung students not far from the university campus.",
                            Image = "",
                            Level = 0,
                            Name = "Szertár",
                            Rent = "2,10,30,90,160,250",
                            Row = 1,
                            SetNumber = 1,
                            Type = 3,
                            UpgradeCost = 50,
                            Value = 60
                        },
                        new
                        {
                            Id = 3,
                            Col = 2,
                            Color = 8,
                            Description = "Community Chest.",
                            Image = "",
                            Level = 0,
                            Name = "Community Chest",
                            Rent = "",
                            Row = 1,
                            SetNumber = 1,
                            Type = 1,
                            UpgradeCost = 0,
                            Value = 0
                        },
                        new
                        {
                            Id = 4,
                            Col = 2,
                            Color = 0,
                            Description = "A jug of Arany Ászok is only 330 HUF.",
                            Image = "",
                            Level = 0,
                            Name = "Bak Egér Borozó",
                            Rent = "4,20,60,180,320,450",
                            Row = 1,
                            SetNumber = 1,
                            Type = 3,
                            UpgradeCost = 50,
                            Value = 60
                        },
                        new
                        {
                            Id = 5,
                            Col = 2,
                            Color = 8,
                            Description = "You were hangover during your exam. Pay your resit cost.",
                            Image = "",
                            Level = 0,
                            Name = "Income Tax",
                            Rent = "100",
                            Row = 1,
                            SetNumber = 1,
                            Type = 4,
                            UpgradeCost = 0,
                            Value = 0
                        },
                        new
                        {
                            Id = 6,
                            Col = 2,
                            Color = 8,
                            Description = ".",
                            Image = "",
                            Level = 0,
                            Name = "Tram 4-6",
                            Rent = "25,50,100,200",
                            Row = 1,
                            SetNumber = 1,
                            Type = 2,
                            UpgradeCost = 0,
                            Value = 200
                        },
                        new
                        {
                            Id = 7,
                            Col = 2,
                            Color = 8,
                            Description = ".",
                            Image = "",
                            Level = 0,
                            Name = "Chance",
                            Rent = "",
                            Row = 1,
                            SetNumber = 1,
                            Type = 0,
                            UpgradeCost = 0,
                            Value = 0
                        },
                        new
                        {
                            Id = 8,
                            Col = 2,
                            Color = 1,
                            Description = "The most famous ruin bar in the world.",
                            Image = "",
                            Level = 0,
                            Name = "Szimpla Kert",
                            Rent = "6,30,90,270,400,550",
                            Row = 1,
                            SetNumber = 1,
                            Type = 3,
                            UpgradeCost = 50,
                            Value = 100
                        },
                        new
                        {
                            Id = 9,
                            Col = 2,
                            Color = 1,
                            Description = "Instant Fogas is certainly the best party hub in not just the party district, but in whole Budapest",
                            Image = "",
                            Level = 0,
                            Name = "Instant Fogas ",
                            Rent = "6,30,90,270,400,550",
                            Row = 1,
                            SetNumber = 1,
                            Type = 3,
                            UpgradeCost = 50,
                            Value = 100
                        },
                        new
                        {
                            Id = 10,
                            Col = 2,
                            Color = 1,
                            Description = "One of the best Jewish restaurants with an amazing looking ruin bar.",
                            Image = "",
                            Level = 0,
                            Name = "Mazel Tov",
                            Rent = "8,40,100,300,450,600",
                            Row = 1,
                            SetNumber = 1,
                            Type = 3,
                            UpgradeCost = 50,
                            Value = 120
                        },
                        new
                        {
                            Id = 11,
                            Col = 2,
                            Color = 8,
                            Description = "This is the jail.",
                            Image = "url('../../assets/jail-tile.png')",
                            Level = 0,
                            Name = "Jail",
                            Rent = "",
                            Row = 2,
                            SetNumber = 1,
                            Type = 5,
                            UpgradeCost = 0,
                            Value = 50
                        },
                        new
                        {
                            Id = 12,
                            Col = 1,
                            Color = 2,
                            Description = "It is the largest covered market in the city.",
                            Image = "",
                            Level = 0,
                            Name = "Great Market Hall",
                            Rent = "10,50,150,450,625,750",
                            Row = 2,
                            SetNumber = 1,
                            Type = 3,
                            UpgradeCost = 100,
                            Value = 140
                        },
                        new
                        {
                            Id = 13,
                            Col = 1,
                            Color = 8,
                            Description = ".",
                            Image = "",
                            Level = 0,
                            Name = "Electric Company",
                            Rent = "4,10",
                            Row = 2,
                            SetNumber = 1,
                            Type = 6,
                            UpgradeCost = 0,
                            Value = 150
                        },
                        new
                        {
                            Id = 14,
                            Col = 1,
                            Color = 2,
                            Description = "It is a large park that offers relaxation and leisure areas for both tourists and residents of Budapest.",
                            Image = "",
                            Level = 0,
                            Name = "Margaret island",
                            Rent = "10,50,150,450,625,750",
                            Row = 2,
                            SetNumber = 1,
                            Type = 3,
                            UpgradeCost = 100,
                            Value = 140
                        },
                        new
                        {
                            Id = 15,
                            Col = 1,
                            Color = 2,
                            Description = "The Citadel is the highest point in Budapest and from it you get the best views of the city.",
                            Image = "",
                            Level = 0,
                            Name = "Citadel",
                            Rent = "12,60,180,500,700,900",
                            Row = 2,
                            SetNumber = 1,
                            Type = 3,
                            UpgradeCost = 100,
                            Value = 160
                        },
                        new
                        {
                            Id = 16,
                            Col = 1,
                            Color = 8,
                            Description = ".",
                            Image = "",
                            Level = 0,
                            Name = "Tram 1",
                            Rent = "25,50,100,200",
                            Row = 2,
                            SetNumber = 1,
                            Type = 2,
                            UpgradeCost = 0,
                            Value = 200
                        },
                        new
                        {
                            Id = 17,
                            Col = 1,
                            Color = 3,
                            Description = "It was initially erected in wood and cardboard for the 1896 exhibition, but was so successful that it was rebuilt using stone and brick.",
                            Image = "",
                            Level = 0,
                            Name = "Hunedoara Castle",
                            Rent = "14,70,200,550,700,900",
                            Row = 2,
                            SetNumber = 1,
                            Type = 3,
                            UpgradeCost = 100,
                            Value = 180
                        },
                        new
                        {
                            Id = 18,
                            Col = 1,
                            Color = 8,
                            Description = "Community Chest.",
                            Image = "",
                            Level = 0,
                            Name = "Community Chest",
                            Rent = "",
                            Row = 2,
                            SetNumber = 1,
                            Type = 1,
                            UpgradeCost = 0,
                            Value = 0
                        },
                        new
                        {
                            Id = 19,
                            Col = 1,
                            Color = 3,
                            Description = "It is one of the most representative squares in Budapest and its statues represent the founders of the country.",
                            Image = "",
                            Level = 0,
                            Name = "Heroes' Square",
                            Rent = "14,70,200,550,700,900",
                            Row = 2,
                            SetNumber = 1,
                            Type = 3,
                            UpgradeCost = 100,
                            Value = 180
                        },
                        new
                        {
                            Id = 20,
                            Col = 1,
                            Color = 3,
                            Description = "it is one of the most important neo-renaissance buildings in Hungary.",
                            Image = "",
                            Level = 0,
                            Name = "Hungarian State Opera House",
                            Rent = "16,80,220,600,800,1000",
                            Row = 2,
                            SetNumber = 1,
                            Type = 3,
                            UpgradeCost = 100,
                            Value = 200
                        },
                        new
                        {
                            Id = 21,
                            Col = 2,
                            Color = 8,
                            Description = "It's your lucky day, you don't have to take the exam.",
                            Image = "url('../../assets/parking-tile.png')",
                            Level = 0,
                            Name = "Offered exam grade",
                            Rent = "",
                            Row = 2,
                            SetNumber = 1,
                            Type = 5,
                            UpgradeCost = 0,
                            Value = 0
                        },
                        new
                        {
                            Id = 22,
                            Col = 2,
                            Color = 4,
                            Description = "It is one of the most beautiful thermal baths in Budapest, the capital city of Hungary.",
                            Image = "",
                            Level = 0,
                            Name = "Gellert Spa",
                            Rent = "18,90,250,700,875,1050",
                            Row = 1,
                            SetNumber = 1,
                            Type = 3,
                            UpgradeCost = 150,
                            Value = 220
                        },
                        new
                        {
                            Id = 23,
                            Col = 2,
                            Color = 8,
                            Description = ".",
                            Image = "",
                            Level = 0,
                            Name = "Chance",
                            Rent = "",
                            Row = 1,
                            SetNumber = 1,
                            Type = 0,
                            UpgradeCost = 0,
                            Value = 0
                        },
                        new
                        {
                            Id = 24,
                            Col = 2,
                            Color = 4,
                            Description = "The Rudas Baths are considered one of the most beautiful Turkish baths in the world.",
                            Image = "",
                            Level = 0,
                            Name = "Rudas Spa",
                            Rent = "18,90,250,700,875,1050",
                            Row = 1,
                            SetNumber = 1,
                            Type = 3,
                            UpgradeCost = 150,
                            Value = 220
                        },
                        new
                        {
                            Id = 25,
                            Col = 2,
                            Color = 4,
                            Description = "The Szechenyi Spa is one of the biggest thermal centers in Europe.",
                            Image = "",
                            Level = 0,
                            Name = "Szechenyi Spa",
                            Rent = "20,100,300,750,925,1100",
                            Row = 1,
                            SetNumber = 1,
                            Type = 3,
                            UpgradeCost = 150,
                            Value = 240
                        },
                        new
                        {
                            Id = 26,
                            Col = 2,
                            Color = 8,
                            Description = ".",
                            Image = "",
                            Level = 0,
                            Name = "Tram 2",
                            Rent = "25,50,100,200",
                            Row = 1,
                            SetNumber = 1,
                            Type = 2,
                            UpgradeCost = 0,
                            Value = 200
                        },
                        new
                        {
                            Id = 27,
                            Col = 2,
                            Color = 5,
                            Description = "The Freedom Bridge in Budapest is considered the third with respect to the permanent bridges of the city and is the shortest of all.",
                            Image = "",
                            Level = 0,
                            Name = "Liberty Bridge",
                            Rent = "22,110,330,800,975,1150",
                            Row = 1,
                            SetNumber = 1,
                            Type = 3,
                            UpgradeCost = 150,
                            Value = 260
                        },
                        new
                        {
                            Id = 28,
                            Col = 2,
                            Color = 5,
                            Description = "It is the third newest bridge of Budapest, Hungary, connecting Buda and Pest across the River Danube.",
                            Image = "",
                            Level = 0,
                            Name = "Erzsébet Bridge",
                            Rent = "22,110,330,800,975,1150",
                            Row = 1,
                            SetNumber = 1,
                            Type = 3,
                            UpgradeCost = 150,
                            Value = 260
                        },
                        new
                        {
                            Id = 29,
                            Col = 2,
                            Color = 8,
                            Description = ".",
                            Image = "",
                            Level = 0,
                            Name = "Water works",
                            Rent = "4,10",
                            Row = 1,
                            SetNumber = 1,
                            Type = 6,
                            UpgradeCost = 0,
                            Value = 150
                        },
                        new
                        {
                            Id = 30,
                            Col = 2,
                            Color = 5,
                            Description = "The Chain Bridge is the oldest bridge in Budapest and the best known on the entire Danube. It is officially known as the Szechenyi Bridge in honor of its creator.",
                            Image = "",
                            Level = 0,
                            Name = "Chain Bridge",
                            Rent = "24,120,360,850,1025,1200",
                            Row = 1,
                            SetNumber = 1,
                            Type = 3,
                            UpgradeCost = 150,
                            Value = 280
                        },
                        new
                        {
                            Id = 31,
                            Col = 2,
                            Color = 8,
                            Description = "It's NOT your lucky day, you have to resit your last exam.",
                            Image = "url('../../assets/go-to-jail-tile.png')",
                            Level = 0,
                            Name = "Go to your re-examination",
                            Rent = "",
                            Row = 2,
                            SetNumber = 1,
                            Type = 5,
                            UpgradeCost = 0,
                            Value = 0
                        },
                        new
                        {
                            Id = 32,
                            Col = 1,
                            Color = 6,
                            Description = "Budapest's most famous catholic church and is located in the heart of the Castle district.",
                            Image = "",
                            Level = 0,
                            Name = "Matthias Church",
                            Rent = "26,130,390,900,1100,1275",
                            Row = 2,
                            SetNumber = 1,
                            Type = 3,
                            UpgradeCost = 200,
                            Value = 300
                        },
                        new
                        {
                            Id = 33,
                            Col = 1,
                            Color = 6,
                            Description = "Its seven towers commemorate the seven founding tribes of Hungary. In charge of defending the city.",
                            Image = "",
                            Level = 0,
                            Name = "Fisherman's bastion",
                            Rent = "26,130,390,900,1100,1275",
                            Row = 2,
                            SetNumber = 1,
                            Type = 3,
                            UpgradeCost = 200,
                            Value = 300
                        },
                        new
                        {
                            Id = 34,
                            Col = 1,
                            Color = 8,
                            Description = "Community Chest.",
                            Image = "",
                            Level = 0,
                            Name = "Community Chest",
                            Rent = "",
                            Row = 2,
                            SetNumber = 1,
                            Type = 1,
                            UpgradeCost = 0,
                            Value = 0
                        },
                        new
                        {
                            Id = 35,
                            Col = 1,
                            Color = 6,
                            Description = "It is also known as the Royal Palace, since it was formerly the residence of the kings of Hungary.",
                            Image = "",
                            Level = 0,
                            Name = "Buda Castle",
                            Rent = "28,150,450,1000,1200,1400",
                            Row = 2,
                            SetNumber = 1,
                            Type = 3,
                            UpgradeCost = 200,
                            Value = 320
                        },
                        new
                        {
                            Id = 36,
                            Col = 1,
                            Color = 8,
                            Description = ".",
                            Image = "",
                            Level = 0,
                            Name = "Tram 19",
                            Rent = "25,50,100,200",
                            Row = 2,
                            SetNumber = 1,
                            Type = 2,
                            UpgradeCost = 0,
                            Value = 200
                        },
                        new
                        {
                            Id = 37,
                            Col = 1,
                            Color = 8,
                            Description = ".",
                            Image = "",
                            Level = 0,
                            Name = "Chance",
                            Rent = "",
                            Row = 2,
                            SetNumber = 1,
                            Type = 0,
                            UpgradeCost = 0,
                            Value = 0
                        },
                        new
                        {
                            Id = 38,
                            Col = 1,
                            Color = 7,
                            Description = "Second most important place in Budapest, dedicated to the first king of Hungary, Saint Stephen.",
                            Image = "",
                            Level = 0,
                            Name = "St. Stephen's Basilica",
                            Rent = "35,175,500,1100,1300,1500",
                            Row = 2,
                            SetNumber = 1,
                            Type = 3,
                            UpgradeCost = 200,
                            Value = 350
                        },
                        new
                        {
                            Id = 39,
                            Col = 1,
                            Color = 8,
                            Description = "You were drunk during your exam. Pay your resit cost.",
                            Image = "",
                            Level = 0,
                            Name = "Super Tax",
                            Rent = "200",
                            Row = 2,
                            SetNumber = 1,
                            Type = 4,
                            UpgradeCost = 0,
                            Value = 0
                        },
                        new
                        {
                            Id = 40,
                            Col = 1,
                            Color = 7,
                            Description = "The third largest parliament in the world and the most emblematic building in Budapest",
                            Image = "",
                            Level = 0,
                            Name = "Parliament",
                            Rent = "50,200,600,1400,1700,2000",
                            Row = 2,
                            SetNumber = 1,
                            Type = 3,
                            UpgradeCost = 200,
                            Value = 400
                        });
                });

            modelBuilder.Entity("Model.Chance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Amount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ChanceCards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = "Parliament",
                            Description = "Advance to Parliament",
                            Type = "advance"
                        },
                        new
                        {
                            Id = 2,
                            Amount = "Go",
                            Description = "Advance to Go (Collect $200)",
                            Type = "advance"
                        },
                        new
                        {
                            Id = 3,
                            Amount = "Szechenyi Spa",
                            Description = "Advance to Szechenyi Spa, if you pass Go, collect $200",
                            Type = "advance"
                        },
                        new
                        {
                            Id = 4,
                            Amount = "Great Market Hall",
                            Description = "Advance to Great Market Hall, if you pass Go, collect $200",
                            Type = "advance"
                        },
                        new
                        {
                            Id = 5,
                            Amount = "Tram",
                            Description = "Advance to the nearest Tram, if unowned, you may buy it from the Bank.",
                            Type = "advance"
                        },
                        new
                        {
                            Id = 6,
                            Amount = "Tram",
                            Description = "Advance to the nearest Tram, if unowned, you may buy it from the Bank.",
                            Type = "advance"
                        },
                        new
                        {
                            Id = 7,
                            Amount = "Utility",
                            Description = "Advance token to nearest Utility, if unowned, you may buy it from the Bank.",
                            Type = "advance"
                        },
                        new
                        {
                            Id = 8,
                            Amount = "50",
                            Description = "Bank pays you dividend of $50",
                            Type = "earn"
                        },
                        new
                        {
                            Id = 9,
                            Amount = "",
                            Description = "Get Out of Jail Free",
                            Type = "jail-card"
                        },
                        new
                        {
                            Id = 10,
                            Amount = "3",
                            Description = "Go back 3 spaces",
                            Type = "back"
                        },
                        new
                        {
                            Id = 11,
                            Amount = "0",
                            Description = "Go directly to Jail, do not pass Go, do not collect $200 ",
                            Type = "jail"
                        },
                        new
                        {
                            Id = 12,
                            Amount = "25",
                            Description = "Make general repairs on all your property, for each level pay $25",
                            Type = "repairs"
                        },
                        new
                        {
                            Id = 13,
                            Amount = "15",
                            Description = "Speeding fine $15",
                            Type = "spend"
                        },
                        new
                        {
                            Id = 14,
                            Amount = "Tram 4-6",
                            Description = "Take a trip to Tram 4-6, if you pass Go collect $200",
                            Type = "advance"
                        },
                        new
                        {
                            Id = 15,
                            Amount = "50",
                            Description = "You have been elected chairman of the board, pay each player $50 ",
                            Type = "spend-each-player"
                        },
                        new
                        {
                            Id = 16,
                            Amount = "150",
                            Description = "Your building loan matures, collect $150 ",
                            Type = "earn"
                        });
                });

            modelBuilder.Entity("Model.Fortune", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Amount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FortuneCards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = "0",
                            Description = "Advance to Go (Collect $200)",
                            Type = "advance"
                        },
                        new
                        {
                            Id = 2,
                            Amount = "200",
                            Description = "Bank error in your favor, collect $200",
                            Type = "earn"
                        },
                        new
                        {
                            Id = 3,
                            Amount = "50",
                            Description = "Doctor's fees, pay $50",
                            Type = "spend"
                        },
                        new
                        {
                            Id = 4,
                            Amount = "0",
                            Description = "Get Out of Jail Free",
                            Type = "jail-card"
                        },
                        new
                        {
                            Id = 5,
                            Amount = "0",
                            Description = "Go directly to jail",
                            Type = "jail"
                        },
                        new
                        {
                            Id = 6,
                            Amount = "10",
                            Description = "It is your birthday Collect $10 from each player",
                            Type = "earn-each-player"
                        },
                        new
                        {
                            Id = 7,
                            Amount = "100",
                            Description = "Life Insurance Matures, collect $100",
                            Type = "earn"
                        },
                        new
                        {
                            Id = 8,
                            Amount = "20",
                            Description = "Income Tax refund, collect $20",
                            Type = "earn"
                        },
                        new
                        {
                            Id = 9,
                            Amount = "100",
                            Description = "Pay Hospital Fees of $100",
                            Type = "spend"
                        },
                        new
                        {
                            Id = 10,
                            Amount = "25",
                            Description = "Receive $25 Consultancy Fee",
                            Type = "earn"
                        },
                        new
                        {
                            Id = 11,
                            Amount = "50",
                            Description = "Pay School Fees of $50",
                            Type = "spend"
                        },
                        new
                        {
                            Id = 12,
                            Amount = "40",
                            Description = "You are assessed for street repairs, $40 per level",
                            Type = "repairs"
                        },
                        new
                        {
                            Id = 13,
                            Amount = "10",
                            Description = "You have won second prize in a beauty contest, collect $10",
                            Type = "earn"
                        },
                        new
                        {
                            Id = 14,
                            Amount = "100",
                            Description = "You inherit $100",
                            Type = "earn"
                        },
                        new
                        {
                            Id = 15,
                            Amount = "50",
                            Description = "From sale of stock you get $50",
                            Type = "earn"
                        },
                        new
                        {
                            Id = 16,
                            Amount = "100",
                            Description = "Holiday Fund matures, receive $100",
                            Type = "earn"
                        },
                        new
                        {
                            Id = 17,
                            Amount = "50",
                            Description = "Pay school fees of $50",
                            Type = "spend"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
