name: Cypress Tests

on: 
  push:
   branches:  
    - '!main'
  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request:
    branches: [ main ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          working-directory: ./TotallyNotMonopolyUI
          install: npm install
          build: npm i -D cypress
          start: npm start
          wait-on: "http://localhost:4200"
          
  create-documentation:
    runs-on: ubuntu-latest
    steps:
      - name: Start Typedoc
        uses: actions-go/push@master
        with:
         working-directory: ./TotallyNotMonopolyUI
         install: npm install
         build: npm i typedoc
         start: npx typedoc
         commit-message: '[Auto] Add documentation'
         remote: main
